#version: '{build}-{branch}'
#
#os: Visual Studio 2019 Preview
#
#install:
#    - wsl sudo sed --in-place 's/focal/groovy/g' /etc/apt/sources.list
#    - wsl sudo apt update
#    - wsl sudo apt install -y g++
#    - git submodule update --init --depth 1
#
#build: off
#
#build_script:
#    - msbuild /t:Build /p:Configuration=Release_except "./exception_perf.sln" -maxcpucount
#    - msbuild /t:Build /p:Configuration=WSL_Release_except "./exception_perf.sln" -maxcpucount
#
#test_script:
#    - '&"./Runtime/win_x64_Release/exception_perf.exe" > exception_benchmark.txt'
#    - more exception_benchmark.txt
#    - wsl /mnt/c/projects/sandbox/Runtime/lin_x86_64_Release/exception_perf.out > exception_benchmark_linux.txt
#    - more exception_benchmark_linux.txt
#
#artifacts:
#  - path: exception_benchmark.txt
#    name: test_results
#  - path: exception_benchmark_linux.txt
#    name: test_results
